### ISSUE TITLE
Why do we have RNScreen sprites table when it doesn't seem to be used any where?

### ISSUE THREAD

**Issue by niom** [ymobe/rapanui#100]
While developing the multilayer feature I started to wonder why we have RNScreen.sprites table and need to manipulate sprite table in

RNScreen:removeRNObject

```
for i = 1, len, 1 do
    if (i == ind) then
        for k = ind + 1, len, 1 do
            self.sprites[k - 1] = self.sprites[k]
            self.sprites[k].idInScreen = k - 1
            self.sprites[k]:getProp().rnObjectId = k - 1
        end
        self.sprites[len] = nil
    end
end
```

and RNScreen:addRNObject

```
self.numSprites = self.numSprites + 1
self.sprites[self.numSprites] = object
object:setIDInScreen(self.numSprites)

object:getProp().rnObjectId = self.numSprites
```

What is the purpose of RNScreen.sprites table? 

if it's not used then it's just adding more complexity to the code and adds a state that needs to be updated manually.

**Comment by MattiaFortunati** [comment]
Hi niom, 
you are right. 
Sprite table is no more used, I thought I removed all its uses but it seems I forgot something ^^
As I can see, in RNScreen there are also some commented code sections regarding it that can be removed, too. 

Thanks for the notice!

**Comment by niom** [comment]
Ok nice to know. Maybe I can remove those code blocks since they make overhead in to my unit tests.

**Comment by niom** [comment]
This bug is redundant since the code has been removed (commented out) in the dev branch. I was developing against Master.
