### ISSUE TITLE
How to create processbar 

### ISSUE THREAD

**Issue by haipq7641** [ymobe/rapanui#101]
How to create processbar  ?
Thank all^^ !

**Comment by MattiaFortunati** [comment]
Hi KaKaVip, 

maybe you are referring to a "progress bar".

Progress bars are made by using lua/Moai coroutines. 
Check this issue for further information:
https://github.com/ymobe/rapanui/issues/88

I'll create a tutorial in the future.

At the moment you can use the code in that issue.

So you should have two coroutines:
one for the the loading bar each step moving and yielding,
one for the GUI loading one piece and then yielding.
