### ISSUE TITLE
newShape using MOAIDraw

### ISSUE THREAD

**Issue by ghost** [ymobe/rapanui#11]
Pull requests are too complicated for me.

Can be called using:
    local circle = R.Factory.newCircle(0,0,100)
    local square = R.Factory.newRect(0,0,100,100)

RNFactory:
http://pastebin.com/zLJK0Le7

RNObject:
http://pastebin.com/jkhXJqmp

Forgive me for using a table to store RN and not using module see..all. (That is why functions are called "R.Object.new()" for example.

I am sure the two functions could be merged.

**Comment by eljeko** [comment]
thank you Andrew

I'll check this,
As usual I'll update the ticket.

**Comment by ghost** [comment]
Now with colour.
https://github.com/anddrewscott/rapanui/commit/6c92d3d96b5b5a97247dd60b1004595e4407e9b7

**Comment by eljeko** [comment]
Hi Andrew did you do some test on performances using locals vs globals?

I checked your fork and I see you changed a lot of scripts to switch to local.

I'll port/merge your code for shapes!

Thank you very much for contribution to Rapanui

**Comment by eljeko** [comment]
Merged your code for shapes!

thank you very much
