### ISSUE TITLE
Map Samples issues

### ISSUE THREAD

**Issue by perroboc** [ymobe/rapanui#112]
I'm trying to learn how to use Tiled maps (tmx) with Moai, but I'm unable to make the samples run succesfully.

For example, I get this error:
.\rapanui-samples/maps/rn-scrolling-physics-map.lua:38: attempt to index global 'aTileset' (a nil value)

I'm using Moai 1.3 and Master Branch Rapanui.

**Comment by eljeko** [comment]
Hi,

Are you testing with a plain version of map samples?

thank you,
Stefano

**Comment by perroboc** [comment]
yeah, as it is from the maps samples folder (rpgmap.tmx). Plain XML file.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0" orientation="orthogonal" width="10" height="15" tilewidth="40" tileheight="40">
 <tileset firstgid="1" name="rpgtileset" tilewidth="40" tileheight="40">
  <image source="rpgtileset.png" width="480" height="280"/>
 </tileset>
 <layer name="ground" width="10" height="15">
  <data>
   <tile gid="6"/>
   <tile gid="6"/>
   <tile gid="13"/>
   <tile gid="14"/>
   <tile gid="14"/>
[...]
```

Al I try to do is run the basic map sample, the same way I run every other sample successfully.
`require("rapanui-samples/maps/rn-basic-map")`

I use win7 x64, currently using ZeroBrane.

**Comment by eljeko** [comment]
Hi,

at the moment rapanui works with moai v1.2 build 35.

I tested with this version of moai on osx on a plain rapanui git checkout and it works.

hth,
Stefano

**Comment by perroboc** [comment]
I'll get that version then, thanks!

**Comment by haipq7641** [comment]
@alvaromunoz send for me v1.2 if you found

Thank you !

**Comment by perroboc** [comment]
I searched for it last night, and couldn't find it :( MOAI doesn't seem to
keep an archive.

On 19-12-2012, at 1:59, KaKaVip notifications@github.com wrote:

@alvaromunoz https://github.com/alvaromunoz send for me v1.2 if you found

Thank you !

—
Reply to this email directly or view it on
GitHubhttps://github.com/ymobe/rapanui/issues/112#issuecomment-11517615.

**Comment by eljeko** [comment]
Hi,

check this out:

https://github.com/moai/moai-dev/tree/Version-1.2-Build-35

hth,
Stefano

**Comment by perroboc** [comment]
Woooot! Thank you!! :D

Sent from my iPhone

On 19-12-2012, at 8:39, Stefano Linguerri notifications@github.com wrote:

Hi,

check this out:

https://github.com/moai/moai-dev/tree/Version-1.2-Build-35

hth,
Stefano

—
Reply to this email directly or view it on
GitHubhttps://github.com/ymobe/rapanui/issues/112#issuecomment-11527156.

**Comment by haipq7641** [comment]
Thank @alvaromunoz , @eljeko !
