### ISSUE TITLE
Issue RNGraphicsManager:deallocateGfx  bramch rapanuidev

### ISSUE THREAD

**Issue by haipq7641** [ymobe/rapanui#115]
I've been experimenting with bramch rapanuidev defect
It can not release texture
On the master bramch, run very well
please fix it

**Comment by MattiaFortunati** [comment]
Hi KaKaVip,
the correct way to remove an asset from the memory is by using

RNFactory.removeAsset(path)

I'm using this with rapanuidev branch and it's working for me.

Let me know.

**Comment by haipq7641** [comment]
Hi MattiaFortunati,
Still error,
i using Moai SDK 1.3r2  + rapanui sdk new version
with rapanuidev branch is problem don't run aScene.onEnd() (Director)
I try to log, but it does not show. But rapanui master branch is show

**Comment by MattiaFortunati** [comment]
It's strange the behaviour is not the same for branch and master.
However it's possible you can encounter some issues using Moai v 1.3r2 because Rapanui is only tested in Moai V1.2 build 35.

**Comment by haipq7641** [comment]
Thank MattiaFortunati,
I try it with Moai V1.2 build 35.
