### ISSUE TITLE
Transition references

### ISSUE THREAD

**Issue by cosmez** [ymobe/rapanui#12]
all the transition demos are having problems when they end.. 

for example

action:setListener(MOAIAction.EVENT_STOP, function() params.onComplete(target) end)

causes the following error 

PANIC: unprotected error in call to Lua API (./RNTransition.lua:134: attempt to call method 'setListener' (a nil value))

**Comment by eljeko** [comment]
Hi cosmez,

On which OS are you testing? which version of MOAI are you using?
Are you running an edited version of the samples?

remember to run the run the samples from the main.lua of rapanui distribution and not the sample script directly.

**Comment by cosmez** [comment]
linux mint x64m moai 
version 0.3 Beta
Revision 1
compiled from source (obviously)
gcc 4.6.1

also, box2D doesnt work properly
ill post more info about that, i just  need to test for  a little bit longer

**Comment by cosmez** [comment]
do you base your code around moai-dev (Development repo)?

because i compiled the moai-beta code... let me see if i can make it work using moai-dev

**Comment by eljeko** [comment]
We are developing on stable releases of moai. 
Anyway we are not testing on linux at all, let me know if you make it works

**Comment by cosmez** [comment]
transitions are fine now

right now im having problems with box2D
all the problems are caused by assertions inside box2D, 

b2PolgonShape::ComputeMass area > 1.19+
b2ContactSolver::b2ContactSolver kNormal > 1.19+

in 

rapanui-samples/physics/rn-physics-shapes

im going to debug it tomorrow with gdb.

**Comment by eljeko** [comment]
ok thank you
