### ISSUE TITLE
how to show dialog in rapanui ???

### ISSUE THREAD

**Issue by homatenbeo1990** [ymobe/rapanui#120]
how to show dialog in rapanui ???

Best Regards
HiepNT

**Comment by MattiaFortunati** [comment]
Hi HiepNT,

I think you are talking about a native dialog, right?
In this case you can use MOAI's

MOAIDialogAndroid
MOAIDialogIOS

I've just opened an issue to wrap these into RapaNui.
https://github.com/ymobe/rapanui/issues/121

**Comment by psdias** [comment]
Hi !

(Sorry for my bad English)

I am a begginer in MOAI, Rapanui and mobile development.

I use Windows 7. I'm trying to run the example
C:\MOAI\moai-sdk\samples\ios\app-dialog\main.lua, but the following message appears:

---

main.lua: 25: attempt to index global 'MOAIDialog' (a nil value)
stack traceback:

##          main.lua: 25 in main chunk

My run.bat file contains the following line:

"c:\MOAI\moai-sdk\bin\win32\moai.exe" "c:/MOAI/moai-sdk/samples/config/config.lua"   "main.lua"
Am I doing something wroing ?

Thank you very much!
Paulo

**Comment by MattiaFortunati** [comment]
Just remember MOAIDialogAndroid is only available while on Android and MOAIDialogIOS is only available for iOS, so you cannot call them from Windows simulator.
This is awkward, that's because we haven't implemented it yet.
