### ISSUE TITLE
Free Box2D Platformer Game Code

### ISSUE THREAD

**Issue by homatenbeo1990** [ymobe/rapanui#124]
I find  Free Box2D Platformer Game Code in Moai forum ( written by Dooms101).
Why not write a tutorial in rapanui ?

Thanks
Link : http://getmoai.com/forums/free-box2d-platformer-game-code-t1415/

**Comment by MattiaFortunati** [comment]
Hi homatenbeo1990,
thanks for your suggestion, great idea! ^^
