### ISSUE TITLE
connect two physics objects

### ISSUE THREAD

**Issue by homatenbeo1990** [ymobe/rapanui#126]
I'm sorry, I'm poor English.

How to connect two physics objects together to them in the same motion.
For example: A is leg, B is the body
A move -> that B also move in A

**Comment by MattiaFortunati** [comment]
Hi,

you can connect bodies by using joints.
You can check this sample for further information:
https://github.com/ymobe/rapanui/blob/master/rapanui-samples/physics/rn-physics-joints.lua

But you should practice with them a little bit if you want to obtain something like QWOP :D

**Comment by homatenbeo1990** [comment]
Thanks  MattiaFortunati
I understand this problem.

But I'm having difficulties in animation.
How to check anim isBusy . 
In my game, character will always run when I press the button and the action will end if I let go.
Please, help me!

I'm sorry, I'm poor English.
