### ISSUE TITLE
Multithreading !

### ISSUE THREAD

**Issue by homatenbeo1990** [ymobe/rapanui#127]
I can not find an example that resolved this issue !
How to use Multithreading in rapanui ?????

My code :
montersThread = MOAIThread.new()
montersThread:run(function()
    while true do
        doNothing ()
        coroutine.yield()
    end
end 
)

if I always call it, my game will lag and break . 

I'm sorry, I'm poor English .
Thanks!
Homatenbeo

**Comment by MattiaFortunati** [comment]
Hi homatenbeo1990, 
you can check this issue:

https://github.com/ymobe/rapanui/issues/88

**Comment by homatenbeo1990** [comment]
Thanks MattiaFortunati.
But my game will lag and break . 

I have a class Monters.
In that class I call montersThread to it always move my character.
But if I am constantly creating Monters, my game will stopworking

I was wrong ????

I'm sorry, I'm poor English .
Thanks!
Homatenbeo
