### ISSUE TITLE
collision remove

### ISSUE THREAD

**Issue by homatenbeo1990** [ymobe/rapanui#128]
My code
--create a function for collision's callbacks
    function onLocalCollide(self, event)
            if (event.self.name == "monters") and 
                           (event.other.name == "bullet") and 
                            (event.phase == "begin") then

```
            x = x - 10
            Log("xxxxxxxxxxxxxxx".. objMonters.blood)
    if x <= 0 then
                   body:remove()
    end 

end
--set the RNBody.collision field to the function you just created
body.collision = onLocalCollide
body:addEventListener("collision")
--you can create as many local collision handlers as you want (one for each object)
```

How to remove addEventListener("collision")  ????

i'm sorry, i'm poor english.
Thanks.
Homatenbeo

**Comment by MattiaFortunati** [comment]
Hi Homatenbeo,

object's collision handler is removed together with the object when you remove it.

If you don't want onLocalCollide to be called anymore just set body.collision to nil:

> body.collision = nil

This shoud work ^^
