### ISSUE TITLE
createanim with createAtlasFromTexturePacker

### ISSUE THREAD

**Issue by homatenbeo1990** [ymobe/rapanui#129]
how to use createAnim with createAtlasFromTexturePacker.
I tried many times, but the error
 . .\rapanui-sdk/RNObject.lua:597: attempt to perform arithmetic on local 'oW' (a nil value)
stack traceback:
    .\rapanui-sdk/RNObject.lua:597 in function 'initWithAnim2'
    .\rapanui-sdk/RNFactory.lua:632 in function 'createAnim'
    .\human/Player.lua:50 in function 'new'
    .\levels/level-1.lua:80 in function 'onCreate'
    .\rapanui-sdk/RNDirector.lua:142 in function 'popIn'
    .\rapanui-sdk/RNDirector.lua:116 in function 'showScene'
    .\scene/play.lua:19 in function 'funct'
    .\rapanui-sdk/RNTimer.lua:60 in function <.\rapanui-sdk/RNTimer.lua:48>

i'm sorry, i'm poor english.
Thanks.
Homatenbeo

**Comment by MattiaFortunati** [comment]
Hi Homatenbeo,
you can check this:
https://github.com/ymobe/rapanui/blob/master/rapanui-samples/atlas/rn-atlas-texture-packer.lua
from line 42 on. :D
