### ISSUE TITLE
categoryBits  , maskBits  and groupIndex in rapanui

### ISSUE THREAD

**Issue by homatenbeo1990** [ymobe/rapanui#133]
how to use categoryBits , maskBits and groupIndex ????

example : object  A,B,C
A and B : group 1 - ( A and B can collide with each other but ca'nt collide C )

Any help much appreciated . 
i'm sorry, i'm poor english.
Thanks.
Homatenbeo

**Comment by MattiaFortunati** [comment]
Hi Homatenbeo,
I'll redirect you to the relative sample:
https://github.com/ymobe/rapanui/blob/rapanuidev/rapanui-samples/physics/rn-physics-filters.lua

**Comment by homatenbeo1990** [comment]
Hi MattiaFortunati
I see your example, but it's still not exactly what I was wondering .

I have C, groupindex = -1
A and B do not put groupindex.
problem : C still collides with A and B.

Any help much appreciated .
i'm sorry, i'm poor english.
Thanks.
Homatenbeo

**Comment by MattiaFortunati** [comment]
You should check box2d documentation.
Also, I found this:
http://stackoverflow.com/questions/936935/box2d-collision-groups

**Comment by homatenbeo1990** [comment]
Hi  MattiaFortunati 
Thanks for share ^^!
