### ISSUE TITLE
Scaling problem

### ISSUE THREAD

**Issue by galsas** [ymobe/rapanui#19]
When you set a different scale than size (in RNScreen:initWith method), after, if you try to access to any Prop for example with a touch event , this fail.

This is solved adding "local x , y = RNFactory.screen.layer:wndToWorld(x, y)" in line 308 of RNInputManager.lua -> method onEvent.

Example:

```
function onEvent(eventType, idx, x, y, tapCount)

local screen = RNFactory.getCurrentScreen()

local x , y = RNFactory.screen.layer:wndToWorld(x, y)

local currenTarget = screen:getRNObjectWithHighestLevelOn(x, y);

local event = RNEvent:new()

event:initWithEventType(eventType)

event.x = x

event.y = y

...
```

**Comment by eljeko** [comment]
Closed with pull merge
