### ISSUE TITLE
RNBody:getMass is missing?

### ISSUE THREAD

**Issue by makotok** [ymobe/rapanui#26]
Hello.

I was looking at the source.
RNBody:getMass is missing?

---

function RNBody:getMass()
    return self.body:getInertia()

**Comment by MattiaFortunati** [comment]
Hi, 

Thanks for having opened an issue.
I've just fixed RNBody, now getMass will call self.body:getMass().
Check my last commit ;D

If everything it's Ok I close the issue.

Thanks!

**Comment by eljeko** [comment]
We close the issue,
if any problem is found please reopen it.
