### ISSUE TITLE
addEventListener on an object does not call function.

### ISSUE THREAD

**Issue by ghost** [ymobe/rapanui#27]
Using RNListeners:
    RNListeners:addEventListener( "touch", func )
does work.

The function I am using:

```
function func()
    print("touched")
end

image = RNFactory.createImage("image.png")
image:addEventListener( "touch", func ) -- RNListeners:addEventListener( "touch", func )
```

**Comment by eljeko** [comment]
We changed the touch system for buttons, anyway I'm fixing/implementing a new approach, your code will work: 
in the new version in the calback function you can write:

``` lua
function func(event)
    print("touched", event.target) 
end

image = RNFactory.createImage("image.png")
image:addEventListener( "touch", func )
```

and the <code>event.target</code> will be the RNObject the function is listening to.

**Comment by ghost** [comment]
I run the new demo. 
The touch function is activated even if I don't click the object itself.

**Comment by eljeko** [comment]
ok,

Working on it.
I'll add two methods:

``` lua

RNObject:addEventListener(eventName, func) -- Will add a call back for all touches inside the RNObject

RNObject:addGlobalEventListener(eventName, func) -- Will add a global listener for all touches
```

for both methods the event.target will be the RNObject the function is listening to.

implemented I only need to test it.

thank you

**Comment by eljeko** [comment]
Hi,
please check the new examples.

let us know!

thanks,
Stefano
