### ISSUE TITLE
RNObject:setY(y),RNObject:setX(x) is missing?

### ISSUE THREAD

**Issue by makotok** [ymobe/rapanui#28]
Hello!

RNObject:setY(y) and RNObject:setX(x) is missing?

``` lua
function RNObject:setX(x)
...
        self.physicObject:setX()
       --  self.physicObject:setX(x) ?
...
end
```

**Comment by ghost** [comment]
The line seems unnecessary as the physical object sticks to the viewed object without this line. 
RNBodie's fieldChangedListener is not being called so I don't know how they are staying together.

**Comment by MattiaFortunati** [comment]
If we want to move the RNObject we should use RNObject.x=value
so if it's a physics obejct 

<pre><code>if key ~= nil and key == "x" then
            self.physicObject:setX(value)
end
</code></pre>


will be called. 

This will move the RNBody and the RNObject which is bound to it.

**Comment by makotok** [comment]
Thank you for answer.

I see no problem in particular in the recognition.
