### ISSUE TITLE
Director + touch event

### ISSUE THREAD

**Issue by Driox** [ymobe/rapanui#29]
case : 
- a director switch 2 scenes with clic on buttons (one button per scene)
- buttons have listeners like btn:setOnTouchDown(handler)
- the listener doesn't work on the 2nd scene

I'm quite new to rapanui so i'm just guessing where the problem is : 
- director creates new scene in RNScreen, self.sprites grows up
- then director destroy the first view, RNScreen:removeRNObject is called and self.sprites reduces HOWEVER rnObjectId isn't change 
- when RNScreen:getRNObjectWithHighestLevelOn is called, the button is never find because rnObjectId > ||self.sprites||

possible solution : add  self.sprites[k]:getProp().rnObjectId = k - 1 in RNScreen, at line 93. I didn't test potential side effects

**Comment by eljeko** [comment]
Hi Driox,

Do you mind to put your code online so we can replicate and test?

thanks in advance!

**Comment by Driox** [comment]
Hi Stefano,

Here is the test case. I comment the potential fix in RNScreen, at line 93.

Regards, 

Adrien

**Comment by eljeko** [comment]
Hi,

No link found in comment, by "Here is the test case" do you mean the opening case comment?

thank you,
Stefano

**Comment by Driox** [comment]
Sry, I just answer the email from github and join a file 

here a real link : https://rapidshare.com/files/872225331/test.zip?bin=1

**Comment by eljeko** [comment]
Hi we are busy on updating RapaNui to new MOAI.

After the update we go on on this.

sorry for delay

**Comment by MattiaFortunati** [comment]
Hey, you can chek 
https://github.com/ymobe/rapanui/blob/rapanuidev/rapanui-samples/menu/rn-menu-director.lua
this will explain how to use director and buttons.

I'll close the issue once this will be on Master branch.

Have Fun,

Mattia
