### ISSUE TITLE
Rnobject.lua:510

### ISSUE THREAD

**Issue by SimonRen** [ymobe/rapanui#30]
Pow2Width, not 'witdh'

**Comment by ghost** [comment]
Are you sure you have the latest source?  line 510 is:
self.pow2Widht, self.pow2Height = self.image:getSize()

https://github.com/ymobe/rapanui/blob/master/rapanui-sdk/RNObject.lua#L510

**Comment by SimonRen** [comment]
Oh, sorry.
I mean that, is the word `pow2Widht' misspelling?
I guess that should be some word like 'pow2Width', but not 'pow2Widht'.

**Comment by ghost** [comment]
Didn't even notice that spelling.
I will make a pull request.

edit:
Made pull:
https://github.com/ymobe/rapanui/pull/31

**Comment by SimonRen** [comment]
Should I close this issue?

I'm switching from svn to git, and still reading the Git documents.

**Comment by MattiaFortunati** [comment]
Thanks for the issue and for the pull request.
I committed the spelling mistake while updating RapaNui to Moai v1.0.

Check the "rapanuidev" branch.

Closed. ;D
