### ISSUE TITLE
MOAI V1.0 MOAIEnvironment.getScreenSize() deprecated

### ISSUE THREAD

**Issue by brendonthrash** [ymobe/rapanui#33]
In MOAI V1.0 the MOAIEnvironment.getScreenSize() was changed to MOAIEnvironment.screenWidth, MOAIEnvironment.screenHeight.

To reflect the changes, RNFactory.lua should be changed to

Line 47: local screenX, screenY = MOAIEnvironment.screenWidth, MOAIEnvironment.screenHeight
Line 49: if screenX ~= nil then --if physical screen

**Comment by eljeko** [comment]
Thank you! 

we are updating rapanui on rapanuidev branch, we put this in the process
