### ISSUE TITLE
PANIC: unprotected error in call to Lua API (RNFactory.lua)

### ISSUE THREAD

**Issue by dotoree** [ymobe/rapanui#34]
In Moai SDK Version 1.0 Revision 3 I get this error:

PANIC: unprotected error in call to Lua API (./rapanui-sdk/RNFactory.lua:47: attempt to call field 'getScreenSize' (a nil value))

Workaround: change

 local screenX, screenY = MOAIEnvironment.getScreenSize()

To

 local screenX = MOAIEnvironment.screenWidth
 local screenY = MOAIEnvironment.screenHeight

**Comment by MattiaFortunati** [comment]
Check the "rapanuidev" branch. We've already fixed this and we are adding new features. I'm currently working on rapanuidev. It works and it's stable and as soon as as we finish to include all the new features we'll merge it to master branch. Thanks. Have Fun

**Comment by dotoree** [comment]
@MattiaFortunati Thank you
