### ISSUE TITLE
Groups in lists causes crash fix

### ISSUE THREAD

**Issue by globalMaxima** [ymobe/rapanui#36]
There is an issue in lists where if you add groups the app crashes on destruction.  The fix is to properly handle the remove() call ot the RNGroup object initiated by the list on removal 

> Following up on this issue.  It looks like when a RNListView is being
> removed it calls v.object:remove on all its elements.  This does not
> work for RNGroup because it has the function:
> 
> function RNGroup:remove(value)
> 
> ```
> self:removeChild(value:getIDInGroup())
> ```
> 
> end
> 
> The fix is to remove each of the groups children.  See below.  (might
> be missing some cleanup here but it looks like it works)
> 
> -- SS. added to properly remove groups from RNListView
> 
> function RNGroup:remove()
> 
> ```
> print("RNGroup:remove(value)")
> 
> print("num children", self.numChildren)
> 
> childrenCount = self.numChildren
> 
> for i = 1, childrenCount do
> 
> print("remove a child", i)
> 
> self.displayObjects[1]:remove()
> 
> end
> ```
> 
> end

**Comment by MattiaFortunati** [comment]
Hi, thanks for having opened an issue. We'll get to this as soon as possible.
