### ISSUE TITLE
Feature request: handle transitions with groups

### ISSUE THREAD

**Issue by guifergon** [ymobe/rapanui#37]
Actually we've modifyed RNTransitions to do something like this with groups and transitions:

for i = 1,myGroup.numChildren do

```
            local PosY = myGroup.displayObjects&[i].y + 1500;

            transition:run(myGroup.displayObjects[i], { type = "move", delay, time = 3500, alpha = 0, y = PosY})

    end
```

end

Only a tip if you would like to add transitions to groups. Thank you!

**Comment by MattiaFortunati** [comment]
I think this should work now. Both in rapanuidev and master, so I can close the issue.
