### ISSUE TITLE
RNSpriteButton

### ISSUE THREAD

**Issue by globalMaxima** [ymobe/rapanui#38]
Would love to see a button widget built into the framework.  Some other frameworks such as cocos2d have pretty handy ones with their menu abstraction.  Main thing needed is a selected and unselected state based on touch.

**Comment by MattiaFortunati** [comment]
We are already working on it. In the meanwhile you can use RNFactory.createAnim() to create an animation. Then you can set object:setOnTouchDown() and setOnTouchUp() on it and set   object.frame=1 or object.frame=2 to change the sprite from pressed to released.
Thank you for having opened an issue.

**Comment by eljeko** [comment]
We added RNButton into the SDK
