### ISSUE TITLE
Removing a jope joint cause crash 

### ISSUE THREAD

**Issue by BlueByLiquid** [ymobe/rapanui#40]
With the following error: 
.\rapanui-sdk/RNJoint.lua:585: attempt to index field 'joint' (a nil value)

Note: this does not happen with Revolute joints though it may happen with others but I have not tested that.

**Comment by MattiaFortunati** [comment]
> this does not happen with Revolute joints though it may happen with others but I have not tested that.

I'm fixing this right now.

EDIT#1: I fixed a problem in Joint creation, but it seems like destroy() method is bugged in Moai for Rope Joints. I'm checking.

EDIT#2: The Rope Joint creation is fixed in rapanuidev branch. However It seems Moai has that bug with Rope Joints. Check this: http://getmoai.com/forums/posting.php?mode=reply&f=7&t=966

I'll keep this issue opened labeled as "bug".

Have a nice day.

**Comment by BlueByLiquid** [comment]
Oh and the link on the moai forum is from me. Is there any way to contact moai?

**Comment by MattiaFortunati** [comment]
> Oh and the link on the moai forum is from me.

Oh, great xD
However I posted some code to help them solving this.

> Is there any way to contact moai?

Via forum, as you already did.

**Comment by BlueByLiquid** [comment]
So I think I figured out why the rope joints aren't working. The last four parameters are acting as offsets not starting and ending points for the joints like previous. So in the case none are provided you would want to use 0, 0, 0, 0 instead of bodyA.x, bodyA.y, bodyB.x, bodyB.y. I would have submitted a pull request but I don't think this is the way it is supposed to work so I am assuming MOAI is going to fix it to work the correct way.
If not changing lines 917-924 to the following fixes it on your end.
        if (anchorAX == nil) then anchorAX = 0
        end
        if (anchorAY == nil) then anchorAY = 0
        end
        if (anchorBX == nil) then anchorBX = 0
        end
        if (anchorBY == nil) then anchorBY = 0
        end

**Comment by MattiaFortunati** [comment]
Do you want me to change those lines now as a temporary fix or we can just wait for Moai's fixes?

Also, if you are sure you fixed a bug into rapanui, use the "pull request" function so we can automatically merge/fix it if it's correct :D

Thanks very much,
have a nice day,

Mattia

**Comment by BlueByLiquid** [comment]
Mattia,

I think those lines are the ones you should change temporarily because they are doing something different than moai is. However the real question is if MOAI will change the code to match what Box2D does or if they will try to be consistent. I looked into the issue and Box2D does not seem to be consistent about the anchors so in the future you might have to change it back but for now I would replace the code I mentioned.

**Comment by MattiaFortunati** [comment]
Ok, thanks.
I've changed these lines so you can continue using updated RapaNui without problems.
I've commented old lines, too.

Have a nice day!

**Comment by BlueByLiquid** [comment]
The crash is still an issue here.

**Comment by MattiaFortunati** [comment]
Hi, 
I don't know if the bug has already been fixed in Moai. And/Or in which version. 
(since they moved development out of gitHub).
I've asked in the forum for any news.

**Comment by BlueByLiquid** [comment]
Wait. Where did they move the development to? I am guessing that is why
there haven't been updates in over a month to the dev repo.

I don't think MOAI has fixed the issue but you can "fix" it by just
removing the delete call. Not ideal but it works.

**Comment by MattiaFortunati** [comment]
> Wait. Where did they move the development to? I am guessing that is why
> there haven't been updates in over a month to the dev repo.

Moai's development is not public no more?
http://getmoai.com/forums/moaikeyboardios-bug-t845/
they moved to "trello"...

> I don't think MOAI has fixed the issue but you can "fix" it by just
> removing the delete call. Not ideal but it works.

I think I'll leave the delete call where it is now, just to remember there is this bug.
(else we'll have some strange glitch/leak, difficult to find).
But yes, if someone really need the rope joint at the moment, he's free to remove the delete call.

**Comment by BlueByLiquid** [comment]
Sounds good on just removing the line.

On the development I think that they just moved issue tracking to trello
(or that is the way that post reads).
