### ISSUE TITLE
Allowing an universal touch listener?

### ISSUE THREAD

**Issue by Sylph** [ymobe/rapanui#43]
Wouldn't it be convenient to also handle all touch event in a single touch handler like in many other sdk as an option. Global universal touch listener is already in, but it'd be convenient for objects to be able to do this too. This way users doesn't have to register four different touch events, further cluttering the code. The user can separate the phases themselves in their touchHandler.

I'm aware that RNObject set a listener on the onTouchCallBackFunction var already, but it doesn't seem to be called.

**Comment by eljeko** [comment]
Hi Sylph,

We added a new method (on rapanuidev branch):

RNObject:setGlobalTouchListener(func)

and sample:

rapanui-sample/touch/rn-touch-buttons-globaltouchlistener.lua

Let us know if it meets your needs!

**Comment by Sylph** [comment]
That'll work perfectly. 
Thank you! :)

I'm also having some trouble figuring out the auto scaling of images, should I open a new issue for that? 

I thought if the config is set properly, then an image following the first 2 values of config.sizes would get upscaled to the last 2 values. I have config.stretch set to true and config.graphics Design set to 960 640. I tested it with an image of 960 640 size. I'll check out the source more.

**Comment by eljeko** [comment]
Hi Sylph,

Yes open a new issue.

Thank you :)

**Comment by MattiaFortunati** [comment]
This change should be on master branch. Issue closed :D
