### ISSUE TITLE
No way to set timestep for Box2D

### ISSUE THREAD

**Issue by BlueByLiquid** [ymobe/rapanui#44]
Unless I am missing something you cannot set the timestep for Box2D. You can certainly set the iterations but not the timestep.

**Comment by MattiaFortunati** [comment]
Hi,

I checked MOAI's documentation here:
http://getmoai.com/docs/class_m_o_a_i_box2_d_world.html

and yes, I don't think we can set the timestep for box2d but just iterations or units at the moment.

Maybe we can open a request within MOAI forum to ask this.
Let me know you you open it, I'll let you know, too ;D

Have a nice day,

Mattia

**Comment by BlueByLiquid** [comment]
Thanks for checking! I had a post in the New Users section about it but have requested that they move it to the bugs now that you also believe there is no method for doing this. I am having lots of trouble without being able to set this and I may have to go back to cocos2D until it is fixed :(

**Comment by MattiaFortunati** [comment]
It's great you posted to Moai forum!

However,remember Moai is opensource, so If you want to set timestep you can access box2d native code and change timestep from there ;D

**Comment by BlueByLiquid** [comment]
Thats a good point about fixing it myself and I probably will. I just really wish MOAI was living up to the "professional SDK" and not just using that to mean no documentation, incomplete and "do most of the work yourself". I keep expecting much more polish. I also haven't seen how to add to the MOAI LUA bindings because the documentation doesn't seem to show anything on this. For example I would like to just add the timestep modification in C and Java and bind it to the Box2D world. The code part is easy but I am new to lua and don't know how the bindings are generated.

**Comment by MattiaFortunati** [comment]
Yes, I agree with you. 
It is not simple nor well documented the way to extend/change Moai.
But a couple of months ago they added MOAIFoo.h and MOAIFoo.mm as an example on how Moai binds together C and Lua. It's still not simple, but it's a point to start from ;D

Have a nice day,
Mattia

**Comment by BlueByLiquid** [comment]
Not sure but it may be setable view MoaiSim.setStep and  setMultiplier(). That seems weird because I would thin tht is related to the actual moai app step not the physics alone. Will be at least a week before I can look at code and see if that is it.

**Comment by BlueByLiquid** [comment]
I have confirmed that setStep seems to do the same functionality but I do have concerns it is not independent of non-physics timings/steps but that is for MOAI proper to fix. So I guess this is not a RapaNui issue and I will close it.

**Comment by MattiaFortunati** [comment]
Ok. Thanks for having investigated this. :D
