### ISSUE TITLE
listview jumps when scrolling up and down past maxy or miny

### ISSUE THREAD

**Issue by stephenmsullivan** [ymobe/rapanui#46]
When you scroll past the max or min y in the RNlistview the list jumps.  

From what I can tell the event.y value returns and jumps 100-200 points when you change direction of the scroll. 

Figured out this is caused by the hard coding of 100 in the line.  

```
                if SELF.deltay > 0 and SELF.y < SELF.options.maxY + 100 or SELF.deltay <= 0 and SELF.y > SELF.options.minY - 100 then
                    if self.beganDelta ~= nil then
                        self.y = event.y - self.beganDelta
                    end
                end
```

**Comment by MattiaFortunati** [comment]
Hi,
thanks for the issue, I should have fix this with my last commit.
https://github.com/ymobe/rapanui/commit/ff4d76ad8f857bcccf9430455e0666f1cb806750

Have Fun!
