### ISSUE TITLE
Translating a group before inserting children into it has no effect

### ISSUE THREAD

**Issue by ruuzo** [ymobe/rapanui#47]
Consider the following code sample - I would've expected rect to render at (100, 100) but it is instead left at (0, 0) (only changing g's position after inserting rect has the desired effect).

``` lua
local g = RNGroup:new()
g.x, g.y = g.x + 100, g.y + 100
local rect = RNFactory.createRect(0, 0, 25, 25)
g:insert(rect)
--g.x, g.y = g.x + 100, g.y + 100

print(g.x, g.y)
```

**Comment by MattiaFortunati** [comment]
Hi ruuzo,
the code you wrote is working correctly:
In RapaNui when you insert an object into a group that object remains at its own coordinates.

If you need to insert the object at group coordinates use resetTransform:

> g:insert(rect,true)

I Hope this can help you.
Let me know!

Have a nice day,
Mattia

NOTE: I've just corrected the resetTransform in rapanuidev branch. Please update your copy of RapaNui. :D

**Comment by ruuzo** [comment]
Hello Mattia, thanks, using your change and resetTransform worked for me...I am trying to convert a Corona project and since Rapanui seems so similar to Corona I was surprised at this difference.

**Comment by MattiaFortunati** [comment]
I'm glad this helped you ^^
Yes, resetTransform is different from Corona one, because our groups are a little bit different ;D
And yes, you can fully port your game from Corona to RapaNui.

Let us know if you encounter other problems/issues.

Have Fun!

Mattia
