### ISSUE TITLE
Texturepacker sample

### ISSUE THREAD

**Issue by meapps** [ymobe/rapanui#48]
I hope some of you can provide a good example how to use Spritesheets.

**Comment by MattiaFortunati** [comment]
Hi, 
check this sample:
https://github.com/ymobe/rapanui/blob/master/rapanui-samples/atlas/rn-atlas-texture-packer.lua

it shows how to create spritesheets from atlases made with Texture Packer and also how to do basic animations with it.

Else check these samples:
https://github.com/ymobe/rapanui/tree/master/rapanui-samples/anim

To have a proper introduction to animations spritesheets without using Texture Packer.

Have a nice day,

Mattia
