### ISSUE TITLE
Support MOAITextBox: spool

### ISSUE THREAD

**Issue by judebert** [ymobe/rapanui#49]
It would be nice to have the Moai TextBox spool functions directly available from RNTextBox.  That would include spool, more, next page, reveal, reveal all, and busy.

**Comment by judebert** [comment]
GitHub is new to me, and I can't see how to mark this as a new feature.  Sorry.

**Comment by MattiaFortunati** [comment]
Hey! 

I can label it, don't worry!
Thanks for the issue!

**Comment by MattiaFortunati** [comment]
Hi,
check this sample:
https://github.com/ymobe/rapanui/blob/rapanuidev/rapanui-samples/basic/rn-text-special.lua

everything should be Ok!

I'll close this issue when everything will be on master branch.

;D
