### ISSUE TITLE
Physics inside of groups causes -x offset when modifying position

### ISSUE THREAD

**Issue by BlueByLiquid** [ymobe/rapanui#58]
If an image is a physics object is added to a group, hen the objects position is modified during the frame update then it causes an -x offset of about 2.03. 

To reproduce. Create a physics image, set a position near the middle top of the screen, add it to a group. Then in the frameupdate handler do something like myObject.y = myObject.y + 1

The object will fall to the left slowly (and down obviously because of the physics). It seems very weird as it doesn't happen unless it is in a group and even odder that it happens even if you only modify the y position (Though it still messes up if you modify the x position only.

**Comment by MattiaFortunati** [comment]
Hi, I've should have fixed this with my last commit.
It was so hard to reproduce, there was a bug in RNBody:setX and RNBody:setY calculating position in a different way than RNBody:getX and RNBody:getY. 
Old and hard to find bug.

I'll close this once rapanuidev will be merged into master.

Thanks for the issue!

;D
