### ISSUE TITLE
RapaNui should be multi Layer

### ISSUE THREAD

**Issue by MattiaFortunati** [ymobe/rapanui#59]
At the moment RapaNui works in a single layer.
It should handle more than one layer instead.

We need like:
RNFactory:addLayer() 
RNFactory:removeLayer() 
and something like a new param in creations:
RNFactory.createImage("image",{layer=layer})--param should be optional to keep compatibility with old projects not using multilayering. Image default behaviour won't change, it will be put on default layer RNFactory.screen

EDIT 1:

niom suggestions:

RNLayer

this class should handle layer creation, storing and removing layers
we should have way to create a layer with and without MOAIPartition -- createLayer -- createLayerWithPartition

RN parts affected by multilayer

1) Initializing screen

When initializing screen we should create the main layer as before
Main layer should be stored to RNLayer (new RN class) these could be done by using the new RNLayer.createLayerWithPartition()

2) Creating a new RNObject from image

we should be able to pass the layer to the image creation and if the layer is missing we should use the main layer
new MOAIProp is added to the layer in RNObject:initWithImage2, so we should be able to pass the layer in that function. Fortunately initWithImage2 takes only one parameter, the image, in so this should be easy.
To support backwards compatibility we should use a new function for createImage, ie. createFromImage(image,layer,parameters) and make the createImage to use createFromImage with main layer

3) Removing RNObject from layer

RNScreen:removeRNObject(object) should be able to take the layer as a parameter so the removed object would be removed from that layer.
in case the layer parameter is not passed then we should remove the object from all of the layers, by using the RNLayer class

EDIT 2:

1) Issue #91 should be considered during the implementation of this feature.

2) Also, a sample folder labeled "multilayer" with a couple of samples on how to use multilayer feature should be good.

**Comment by niom** [comment]
I would like to support this idea. Multi layer feature is needed for handling HUD with Camera.

**Comment by niom** [comment]
I've been trying to solve how we could make RapaNui multilayered and have found at least three cases which would be affected by the multilayer feature and we probably need a new RN class to handle the layers.

RNLayer
- this class should handle layer creation, storing and removing layers
- we should have way to create a layer with and without MOAIPartition
  -- createLayer
  -- createLayerWithPartition 

RN parts affected by multilayer
1) Initializing screen
- When initializing screen we should create the main layer as before
- Main layer should be stored to RNLayer (new RN class)
  these could be done by using the new RNLayer.createLayerWithPartition()

2) Creating a new RNObject from image
- we should be able to pass the layer to the image creation and if the layer is missing we should use the main layer
- new MOAIProp is added to the layer in RNObject:initWithImage2, so we should be able to pass the layer in that function. Fortunately initWithImage2 takes only one parameter, the image, in so this should be easy.
- To support backwards compatibility we should use a new function for createImage, ie. createFromImage(image,layer,parameters) and make the createImage to use createFromImage with main layer

3) Removing RNObject from layer
- RNScreen:removeRNObject(object) should be able to take the layer as a parameter so the removed object would be removed from that layer.
- in case the layer parameter is not passed then we should remove the object from all of the layers, by using the RNLayer class

Should we consider any other parts which would be affected by the multilayer feature or could this be the minimun viable feature considering the multilayer?

**Comment by niom** [comment]
I'm working with an implementation for this. It's going to take at least few days so stay tuned.

**Comment by eljeko** [comment]
Great, remember to submit patch on dev branch, 

thank you for your help!

**Comment by skaflux** [comment]
This will be great! I'm currently stuck on something because I want to have separate layers. Thanks!

**Comment by niom** [comment]
Sorry we only made one sample for the multilayer. How to create a HUD with another layer and how that behaves with camera and camera movement. @skaflux did you have some other idea where to use the multilayer? Maybe you could provide a sample from your requirements?

**Comment by MattiaFortunati** [comment]
Hey guys,

I've merged, reviewed and extended the multilayer feature.

https://github.com/ymobe/rapanui/commit/5a4896c5df4a454c0b0c444e91f429f0f3b59a0e

Thanks for all your efforts!

**Comment by skaflux** [comment]
@niom What I'm trying to do is to give the appearance of depth in the 2D world. Lets say 4 layers. Layer 1 is the background image. Layer 2 has background objects flying around. Layer 3 is the game layer where collisions are happening. Layer 4 has the GUI elements. Does this make any sense?

Thanks!

**Comment by ghost** [comment]
I'm attempting to take a layer from a map loaded through RNMapFactory, insert the player into the layer, and apply one of Moai's prebuilt sorts [ layer:setSortMode ( MOAILayer2D.SORT_VECTOR_ASCENDING ) ]

The trouble is the only time RN seems to expose itself to MOAILayer is in RNLayer, but RNMapLayer is unconnected to RNLayer. Should I even be approaching the problem from this angle?
