### ISSUE TITLE
string subscript out of range

### ISSUE THREAD

**Issue by ghost** [ymobe/rapanui#6]
maybe I run it wrong but each time I get:

http://screensnapr.com/v/2LkJSE.png

**Comment by eljeko** [comment]
Hi, Are you building Moai from source?
We are developing rapanui both on osx and winxp.
On winxp we use the prebuilt exe, on osx we build moai for ios from source.

Anyway the error you get it's not a lua related, if you give us some datails we will try to reproduce it.

thank you

**Comment by ghost** [comment]
Win32 building from source

note. I can not built Moai ATM because tinyxml.lib can not be read (as visual basic tells me) - thinking about it, that is probably the reason.

**Comment by eljeko** [comment]
Ok, keep us up to date about this.

thank you

**Comment by ghost** [comment]
I used prebuilt moai. Works now, sorry for making a fuss.

**Comment by eljeko** [comment]
Don't worry

Thank you
