### ISSUE TITLE
RNTimer sample

### ISSUE THREAD

**Issue by meapps** [ymobe/rapanui#61]
How can i use a timer that repeats only one time? It would be easier for some turnbase games...

**Comment by eljeko** [comment]
Hi,

Use this  code (change iterations value)

``` lua
times = 0
local background = RNFactory.createImage("images/background-purple.png")

local iterations = 10

text = RNFactory.createText("Gone run: ", { size = 20, top = 5, left = 5, width = 200, height = 50 })

local function count()
    times = times + 1
    text:setText("Gone run: " .. times)
end

local actionId = RNMainThread.addTimedAction(0.5, count, iterations)


```

I will add this sample to rapanui.

Remember to remove the timed action using the actionId you receive when you call  RNMainThread.addTimedAction(0.5, count, iterations)

thank you,
Stefano

**Comment by meapps** [comment]
thank you... for the help
