### ISSUE TITLE
Animated Button Feature

### ISSUE THREAD

**Issue by meapps** [ymobe/rapanui#64]
I really miss the feature to use one sheet for different button, maybe a combination from anim sample with a button...

**Comment by MattiaFortunati** [comment]
Hi,

why did you closed this issue? Have you resolved this already?

**Comment by meapps** [comment]
Because i found minutes later in the touch folder a sample that covered most things its called rn-animated button

**Comment by MattiaFortunati** [comment]
Ok!

If this sample is solving your issue we can close this issue again ^^
