### ISSUE TITLE
RNPhysics line change 'request'

### ISSUE THREAD

**Issue by ghost** [ymobe/rapanui#7]
in RNPhysics, change line 189 to

fixture = body:addCircle(0, 0, tempFixture.radius)

This allows you to set the radius by

RNPhysics.createBodyFromImage(image, {radius=10})

I think this was the intended function as that is all that has to be changed. I could probably pushed this to you, but I don't understand git as of yet too well.

Andrew

**Comment by MattiaFortunati** [comment]
Thank you, I will fix this in the next commit. ^^

**Comment by MattiaFortunati** [comment]
Done! Togheter with some fixes to upgrade to box2d 2.2.1 of MOAI beta 9.

Enjoy it and forgive me if RapaNui doesn't still handle box2d 2.2.1 completely.

Mattia

**Comment by MattiaFortunati** [comment]
Close
