### ISSUE TITLE
setLevel doesn't work on text

### ISSUE THREAD

**Issue by BlueByLiquid** [ymobe/rapanui#70]
It seems to just be where it want to. There isn't a crash it just seems to be ignored.

**Comment by MattiaFortunati** [comment]
Mh... 

> RNText:setLevel(value) 

is working for me.

**Comment by BlueByLiquid** [comment]
You are correct it is another bug with text which was making it appear not to be set (unlikely someone else would notice this issue but I was doing something funny with setLevel). closing
