### ISSUE TITLE
Ability to set easing parameters on RNTransitions

### ISSUE THREAD

**Issue by BlueByLiquid** [ymobe/rapanui#72]
It would be really nice to be able to set the easing parameters for transitions. For example sometimes you want to instantly start rotation or use a different lead in method. Something like cocos2d would be very helpful: http://www.cocos2d-iphone.org/wiki/doku.php/prog_guide:actions_ease#ease_actions

Is there a way to make it constant?

**Comment by MattiaFortunati** [comment]
Hi,

you can use MOAI's ease types in RNTransitions, for example:

> RNTransition(object, { type = "move", mode =MOAIEaseType.EASE_IN})

You can find a list of MOAI's ease types here:
http://getmoai.com/docs/class_m_o_a_i_ease_type.html

There is no way, at the moment, to make this global.

;D

**Comment by BlueByLiquid** [comment]
That is what I am looking for thanks! Might be nice to set it globally since it seems to use I think ease in by default
