### ISSUE TITLE
ScreenStretch REFACTORING needed

### ISSUE THREAD

**Issue by MattiaFortunati** [ymobe/rapanui#77]
Since we need improvement in stretch feature we need a refactoring.
In config.lua, stretch section, we should have:

config.stretch={status=true,mode="letterbox",drawOnBlackBars=false,graphicsDesign={w=640,h=960}}

status--> boolean, to known when we need to apply stretch.
mode --> "letterbox" or "fullscreen"  to know when to use letterbox or fullscreen type.
letterbox=true--> whether to have blackbars or full screen stretch 
drawOnBlackBars--> whether user can draw on blackbars.
graphicsDesign--> sizes your assets are originally designed for.

New features are:

> mode

It should be simple to handle: at the moment, game is letterboxed by default. If it's "fullscreen", in RNFactory, instead of calculate black bars spaces we should simply stretch the viewport size to the device screen size. Aspect Ratio is ignored.

> drawOnBlackBars=false

At the moment , we cannot draw on black bars, because viewport is created as large as screen and then stretched to the right size to follow aspect ratio. This will give game black bars. This will automatically cut the sprites when outside the "game space".
With drawOnBlackBars enabled the follow should be done:
viewport should be created as large as screen plus enough space to cover black bars spaces when it will be stretched to follow aspect ratio. So we'll have game running on the center of the screen(as when we cannot draw on bars) but viewport as large as every device screen. This won't automatically cut off the sprites when outside "game space". (but we can use scissorRect).

**Comment by Sylph** [comment]
We  could also just refactor stretch so that you can set 
config.stretch = "stretch" -> Just stretch to the entire screen
config.stretch = "letterbox" -> w/ black bars on the side
rather than using boolean?

I have no preference myself, but that's less variables to keep track of

**Comment by MattiaFortunati** [comment]
You are right, signature was awful ;P
I updated it, and maybe I'll change it again later ^^

**Comment by Sylph** [comment]
my fork already implement that now. If you think the other way is better, i'll revert to that later. :)

**Comment by MattiaFortunati** [comment]
Ok, I've refactored it in my last commit.
It should be exactly as the one in your fork.
Have fun!

(as ever, I'll close the issue once everything will be on master branch)

**Comment by Sylph** [comment]
I just merged those changes, and they work perfectly.

I was thinking of adding that full stretch capability, but I wasn't sure. It's definitely a good one to add to give more options. :)
