### ISSUE TITLE
Rapanui Master : Config > Stretch not working

### ISSUE THREAD

**Issue by dyoxyne** [ymobe/rapanui#89]
Hello,

I'm not sure if I'm right and if it's here I should post this remark.

The samples are not streched even if there is in the config file : 

config.stretch = { status = true, letterbox = true, drawOnBlackBars = false, graphicsDesign = { w = 640, h = 960 } }

Thanks.

**Comment by MattiaFortunati** [comment]
Hi dyoxyne,

this is my configuration and it's actually working:

config.sizes["iPhone3G"] = { 320, 480, 320, 480 } --I want to use a 320x480 screen
config.device = "iPhone3G"--I want to use a 320x480 screen
config.stretch = { status = true, letterbox = true, drawOnBlackBars = false, graphicsDesign = { w = 640, h = 960 } }--I want a stretch, with letterbox mode on and my graphics are designed for 640x960, so my graphics half their size and fixe the screen

I've also just made some testing and everything seems to work fine. Samples are correctly working for me.
What are your configuration and graphics sizes?

**Comment by dyoxyne** [comment]
Hello Mattia,

Thanks for your quick answer.
Sorry for wasting your time, I managed to stretch the screen. The graphicsDesign value was by default 640 \* 960 but the examples were 320 \* 480.

So I wrote : config.stretch = { status = true, letterbox = true, drawOnBlackBars = false, graphicsDesign = { w = 320, h = 480 } } for stretching the examples.

**Comment by MattiaFortunati** [comment]
Don't worry dyoxyne, that's why we need docs for RapaNui ;D

Glad to help!
Have a nice day!
