### ISSUE TITLE
Groups inside groups

### ISSUE THREAD

**Issue by ghost** [ymobe/rapanui#9]
```
Group = RNGroup:new()
Group2 = RNGroup:new()
Group:insert(Group2)
```

Will print:
PANIC: unprotected error in call to Lua API (...and Settings\Andrew\Desktop\moai work\RN\RNGroup.lua:123: attempt to call method 'setParentGroup' (a table value))

**Comment by eljeko** [comment]
As far as for now there is no support for nested groups (but on the todo list), we will protect the function to avoid crash in next releases. We leave this issue open.
thank you

**Comment by MattiaFortunati** [comment]
Hi,
check out my latests commits on branch rapanuidev.
In this sample:
https://github.com/ymobe/rapanui/blob/rapanuidev/rapanui-samples/groups/rn-groups-basics.lua
is shown how to nest groups inside groups and some other test for removing, transitions and more.
Have Fun ^^

**Comment by Sylph** [comment]
That's great! So I don't have to write it myself/use other SDKs. :)
With this and the full spritesheet support, there are very few minor reasons left to use any other SDKs. ^^

Thanks for the hard work ^^

**Comment by MattiaFortunati** [comment]
Very nice! 
I'm glad to hear this, thank you.

Have a nice day!
